apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: nginx-rs
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs-pod
  template:
    metadata:
      labels:
        app: nginx-rs-pod
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP

